Block main branch commit #41

diff --git a/lefthook.yml b/lefthook.yml
--- a/lefthook.yml
+++ b/lefthook.yml
@@ -1,6 +1,16 @@
 pre-commit:
   parallel: true
   commands:
+    block-main-branch-commit:
+      run: |
+        current_branch="$(git branch --show-current)"
+
+        if [ "$current_branch" = "main" ]; then
+          echo "Error: Direct commits to the main branch are not allowed."
+          exit 1
+        else
+          echo "This is not the main branch, so commits are allowed."
+        fi
     cargo-clippy:
       run: cargo clippy -- -D warnings
     cargo-fmt:
@@ -10,6 +20,19 @@ pre-commit:
 pre-push:
   parallel: true
   commands:
+    check-for-conflicts:
+      run: |
+        echo "Checking for conflicts with the remote main branch..."
+
+        git fetch origin main
+
+        if git merge-base --is-ancestor HEAD origin/main; then
+          echo "No conflicts detected. Proceeding with push."
+        else
+          echo "Error: Conflicts detected with the remote main branch."
+          echo "Please resolve conflicts before pushing again."
+          exit 1
+        fi
     cargo-audit:
       run: cargo audit
     cargo-outdated:
